spring:
  application:
    name: vente-chaussure
  datasource:
    username: ventechaussure
    password: ventechaussure
    url: jdbc:mysql://localhost:3306/ventechaussure
  jpa:
    hibernate:
      #ddl auto:create permet de supprimer et de creer les tables a chaque execution
      ddl-auto: create

    show-sql: true
server:
  port: 1234